### ISSUE TITLE
Question Regarding Analysis of Mean effects GWAS

### ISSUE THREAD

**Issue by akhilpampana** [DecodeGenetics/gnonadd#8]
Hello,

I am attempting to conduct this analysis on a dataset that contains around 15,000 individuals and would like to perform a GWAS of mean effects using SAIGE instead of BOLT-LMM. I have a few questions:

- Have you tested SAIGE for GWAS of mean effects?
- You have regressed out the variables, and inverse rank-normalized residuals were used. Have you made any adjustments with covariates after the INT method was performed for GWAS?
- How were the mean effects calculated? Have you compared them with any other tools?
- Is it possible to perform this analysis without using IRNT?

Regards
Akhil

**Comment by gumeo** [comment]
Sorry, just noticed this issue, will get back with answers!

**Comment by gumeo** [comment]
Thanks for the questions, some answers to your questions, and further questions, since I don't completely understand the last one.

1) We have not tried SAIGE for this analysis yet.
2) No further adjustments.
3) I'm not sure what you mean, instead of additive model computing mean per genotype?
4) Do you mean INT? As in inverse normal transform?

**Comment by akhilpampana** [comment]
Hello Gumeo,

Thank you so much for the response. 

I'm not sure what you mean, instead of additive model we compute a full model, so mean per genotype.
 - I mean to ask how you calculated mean effects. 

Do you mean INT? As in inverse normal transform?
 - Yes

Regards
Akhil

**Comment by gumeo** [comment]
To clarify the first point. Sorry, the last answer was not correct. When we refer to mean effects GWAS we are talking about an additive mean GWAS, (the wording used is to contrast it with the variance effect GWAS). We also investigate deviations from the additive model, e.g. the dominance model (see section in article _Dominance effects in blood lipids_). The dominance effects are only computed on variants found from the mean effect analysis (additive GWAS). Thus the mean effects reported, are traditional additive mean effects, whereas the dominance effects reported are deviations from this model. Since the dominance effects were estimated only for a handful of variants we were able to do that using R.

The second point, concerning the INT. The INT has become standard practice in genetics. It is definitely possible to do this without the INT, but deviations from normality, can create spurious associations.

**Comment by akhilpampana** [comment]
Thank you so much. I will test the INT with and without in saige to see if there is a difference.
